[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections]
      [entryPoints.web.http.redirections.entryPoint]
        to = "websecure"
        scheme = "https"

  [entryPoints.websecure]
    address = ":443"
    [entryPoints.websecure.http.tls]
      certResolver = "letsencrypt"

[certificatesResolvers]
  [certificatesResolvers.letsencrypt.acme]
    email = "admin@fordrunners.club"
    storage = "/etc/letsencrypt/acme.json"
    [certificatesResolvers.letsencrypt.acme.httpChallenge]
      entryPoint = "web"

[providers.docker]
  exposedByDefault = false

